# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  vmImage: 'windows-latest'

steps:
  - task: UseNode@1
    inputs:
      version: '18.x'

  - script: |
      npm install
      npm run make
    displayName: 'Install dependencies & build'

  - script: npm run make
    displayName: 'Publish Electron App'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'electron-build'
      publishLocation: 'Container'

  - task: UniversalPackages@0
    displayName: Publish
    inputs:
      command: publish
      publishDirectory: '$(Build.ArtifactStagingDirectory)'        ## Location of the files you wish to publish
      vstsFeedPublish: 'setools-feeds'                ## The project and feed name to publish to. If you're working with an organization-scoped feed, specify only the feed name
      vstsFeedPackagePublish: 'SETools'                     ## The package name. Must be lower case. Use only letters, numbers, and dashes
      packagePublishDescription: 'Making Case Communication Easier'           ## Description of the package content
      versionOption: custom                                             ## Select a versioning strategy. Options: `major`, `minor`, `patch`, `custom`
      versionPublish: '1.0.1'                               ## The custom package version
      packagePublishDescription: 'Making Communication Easier'                ## Description of the package content

